### ISSUE TITLE
Slack notifications from GHA

### ISSUE THREAD

**Issue by ricky-undeadcoders** [grafana/shared-workflows#113]

**Comment by ricky-undeadcoders** [comment]
[Design Doc](https://docs.google.com/document/d/16ivL1m_AA-SjwG5vbLeolBDfAhBdzQr2kYE4yoEnnzQ/edit#heading=h.5sybau7waq2q)

**Comment by ricky-undeadcoders** [comment]
It sure looks like [proposal 2](https://github.com/slackapi/slack-github-action?tab=readme-ov-file#technique-2-slack-app) from the design doc works. I added the following to an existing GHA action and add a SLACK_BOT_TOKEN as a repo secret (which has since been deleted). I got a Slack notification in #slack-webhooks-test; which does not have a webhook already set up.

```
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
          channel-id: 'C01DGCDDLDP' # slack-webhooks-test
          # For posting a simple plain text message
          slack-message: "Test GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
```


![Image](https://github.com/grafana/shared-workflows/assets/21371729/846f0871-6c29-4b3c-8f4b-1ffbbcb0de7b)

![Image](https://github.com/grafana/shared-workflows/assets/21371729/e3fce7f1-19fc-4db4-9de3-82f91938f6f3)
