### ISSUE TITLE
`trigger-argo-workflow` does not print the workflow url until the workflow completion when `--wait` flag is used

### ISSUE THREAD

**Issue by fornfrey** [grafana/shared-workflows#70]
When submitting a workflow with the `--wait` flag, the process blocks until the workflow is completed. This results in the workflow URL being printed to the output only after workflow completion. 

Sample job output to compare the time of logs:
```
Notice: running command
  time: "2024-03-18T15:26:48.022Z"
  level: INFO
  extraArgs:
  - --wait
Notice: workflow URI
  time: "2024-03-18T15:35:27.592Z"
  level: INFO
  uri: https://argo-workflows/workflows/k6-cloud-cd/my-workflow-1
```
