### ISSUE TITLE
Update example workflows to be compliant with zizmor

### ISSUE THREAD

**Issue by dblinkhorn** [grafana/shared-workflows#955]
In the get-vault-secrets workflow example we are telling people to set top-level permissions like this:

```yaml
name: CI
on:
  pull_request:

# These permissions are needed to assume roles from Github's OIDC.
permissions:
  contents: read
  id-token: write
```

But this will be flagged by zizmor as "overly broad permissions". They should instead be defined at the job level:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    # These permissions are needed to assume roles from Github's OIDC.
    permissions:
      contents: read
      id-token: write
    steps:
      - id: get-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@get-vault-secrets-v1.2.0
        with:
          # Secrets placed in the ci/common/<path> path in Vault
          common_secrets: |
            ENVVAR1=test-secret:testing
          # Secrets placed in the ci/repo/grafana/<repo>/<path> path in Vault
          repo_secrets: |
            ENVVAR2=test-secret:key1
```

There are probably other places where our examples disagree with zizmor linting, but haven't checked thoroughly yet.
